// Generated from: tests\features\02Mypatients.feature
import { test } from "../../../tests/fixtures/customFixtures.js";

test.describe('My Patient Page', () => {

  test.beforeEach('Background', async ({ Given, When, And, myPatientPageFixture }, testInfo) => { if (testInfo.error) return;
    await Given('User is logged into the application', null, { myPatientPageFixture }); 
    await And('User is in dietician application dashboard page', null, { myPatientPageFixture }); 
    await When('User clicks on My Patients button', null, { myPatientPageFixture }); 
  });
  
  test('Verify page header and search components', async ({ Then, And, myPatientPageFixture }) => { 
    await Then('Page header "My Patients" should be displayed', null, { myPatientPageFixture }); 
    await And('Search bar should be displayed', null, { myPatientPageFixture }); 
    await And('Search icon should be displayed inside the search bar', null, { myPatientPageFixture }); 
    await And('Placeholder text "Search..." should be displayed', null, { myPatientPageFixture }); 
  });

  test('Verify patient table headers and sorting icons', async ({ Then, And, myPatientPageFixture }) => { 
    await Then('following table headers should be displayed', {"dataTable":{"rows":[{"cells":[{"value":"Patient Id"}]},{"cells":[{"value":"Name"}]},{"cells":[{"value":"Details"}]},{"cells":[{"value":"Last Visit Date"}]},{"cells":[{"value":"Actions"}]},{"cells":[{"value":"Edit/Delete"}]}]}}, { myPatientPageFixture }); 
    await And('following columns should have sorting icons', {"dataTable":{"rows":[{"cells":[{"value":"Patient Id"}]},{"cells":[{"value":"Name"}]}]}}, { myPatientPageFixture }); 
  });

  test('Verify patient table data and details column', async ({ Then, And, myPatientPageFixture }) => { 
    await Then('All columns should have values', null, { myPatientPageFixture }); 
    await And('each patient record should contain', {"dataTable":{"rows":[{"cells":[{"value":"Patient Id"}]},{"cells":[{"value":"Patient Name"}]}]}}, { myPatientPageFixture }); 
    await And('Details column should display following for each patient', {"dataTable":{"rows":[{"cells":[{"value":"phone number"}]},{"cells":[{"value":"email"}]},{"cells":[{"value":"date of birth"}]}]}}, { myPatientPageFixture }); 
    await And('Details should be displayed in multiline format', null, { myPatientPageFixture }); 
  });

  test.describe('Validate field formats in patient details', () => {

    test('Example #1', async ({ Then, myPatientPageFixture }) => { 
      await Then('"Email" should be displayed in "valid email" format for each patient record', null, { myPatientPageFixture }); 
    });

    test('Example #2', async ({ Then, myPatientPageFixture }) => { 
      await Then('"Phone number" should be displayed in "valid digits" format for each patient record', null, { myPatientPageFixture }); 
    });

    test('Example #3', async ({ Then, myPatientPageFixture }) => { 
      await Then('"Date of birth" should be displayed in "dd-mm-yyyy" format for each patient record', null, { myPatientPageFixture }); 
    });

    test('Example #4', async ({ Then, myPatientPageFixture }) => { 
      await Then('"Last visit date" should be displayed in "dd-mm-yyyy" format for each patient record', null, { myPatientPageFixture }); 
    });

  });

  test('Verify actions and icons for each patient row', async ({ Then, And, myPatientPageFixture }) => { 
    await Then('following actions should be available for each patient', {"dataTable":{"rows":[{"cells":[{"value":"View Previous Test Reports"}]},{"cells":[{"value":"View Previous Diet Plans"}]},{"cells":[{"value":"Create New Report/plan"}]}]}}, { myPatientPageFixture }); 
    await And('Edit icon should be displayed for each patient record', null, { myPatientPageFixture }); 
    await And('Delete icon should be displayed for each patient record', null, { myPatientPageFixture }); 
  });

  test('Verify My Patients page when no patient exists', async ({ Given, When, Then, And, myPatientPageFixture }) => { 
    await Given('User logged into the application without patient records', null, { myPatientPageFixture }); 
    await And('User is in dietician application dashboard page', null, { myPatientPageFixture }); 
    await When('User clicks on My Patients button', null, { myPatientPageFixture }); 
    await Then('My Patients page should display empty table', null, { myPatientPageFixture }); 
  });

  test.describe('Verify column sorting functionality', () => {

    test('Example #1', async ({ Given, When, Then, myPatientPageFixture }) => { 
      await Given('User is in My Patients page', null, { myPatientPageFixture }); 
      await When('User clicks "up" arrow on "Patient Id" column', null, { myPatientPageFixture }); 
      await Then('Patient records should be sorted in "ascending" order by "Patient Id"', null, { myPatientPageFixture }); 
    });

    test('Example #2', async ({ Given, When, Then, myPatientPageFixture }) => { 
      await Given('User is in My Patients page', null, { myPatientPageFixture }); 
      await When('User clicks "down" arrow on "Patient Id" column', null, { myPatientPageFixture }); 
      await Then('Patient records should be sorted in "descending" order by "Patient Id"', null, { myPatientPageFixture }); 
    });

    test('Example #3', async ({ Given, When, Then, myPatientPageFixture }) => { 
      await Given('User is in My Patients page', null, { myPatientPageFixture }); 
      await When('User clicks "up" arrow on "Name" column', null, { myPatientPageFixture }); 
      await Then('Patient records should be sorted in "ascending" order by "Name"', null, { myPatientPageFixture }); 
    });

    test('Example #4', async ({ Given, When, Then, myPatientPageFixture }) => { 
      await Given('User is in My Patients page', null, { myPatientPageFixture }); 
      await When('User clicks "down" arrow on "Name" column', null, { myPatientPageFixture }); 
      await Then('Patient records should be sorted in "descending" order by "Name"', null, { myPatientPageFixture }); 
    });

  });

  test.describe('Verify search functionality', () => {

    test('Example #1', async ({ Given, When, Then, myPatientPageFixture }) => { 
      await Given('User is in My Patients page', null, { myPatientPageFixture }); 
      await When('User searches using "patient name"', null, { myPatientPageFixture }); 
      await Then('Matching patient details should be displayed', null, { myPatientPageFixture }); 
    });

    test('Example #2', async ({ Given, When, Then, myPatientPageFixture }) => { 
      await Given('User is in My Patients page', null, { myPatientPageFixture }); 
      await When('User searches using "patient id"', null, { myPatientPageFixture }); 
      await Then('Matching patient details should be displayed', null, { myPatientPageFixture }); 
    });

  });

  test('Verify clearing search restores all records', async ({ Given, When, Then, And, myPatientPageFixture }) => { 
    await Given('User is in My Patients page', null, { myPatientPageFixture }); 
    await And('User entered text in search box', null, { myPatientPageFixture }); 
    await When('User clears the search text', null, { myPatientPageFixture }); 
    await Then('All patient records should be displayed again', null, { myPatientPageFixture }); 
  });

  test.describe('Verify pagination navigation', () => {

    test('Example #1', async ({ Given, When, Then, myPatientPageFixture }) => { 
      await Given('User is in "multiple pages of patient records" of My Patients page', null, { myPatientPageFixture }); 
      await When('User clicks "next page (>)" arrow', null, { myPatientPageFixture }); 
      await Then('"Next set of patient records" should be displayed', null, { myPatientPageFixture }); 
    });

    test('Example #2', async ({ Given, When, Then, myPatientPageFixture }) => { 
      await Given('User is in "last page" of My Patients page', null, { myPatientPageFixture }); 
      await When('User clicks "previous page (<)" arrow', null, { myPatientPageFixture }); 
      await Then('"Previous set of patient records" should be displayed', null, { myPatientPageFixture }); 
    });

    test('Example #3', async ({ Given, When, Then, myPatientPageFixture }) => { 
      await Given('User is in "any page except first" of My Patients page', null, { myPatientPageFixture }); 
      await When('User clicks "first page (<<)" arrow', null, { myPatientPageFixture }); 
      await Then('"First page of patient records" should be displayed', null, { myPatientPageFixture }); 
    });

    test('Example #4', async ({ Given, When, Then, myPatientPageFixture }) => { 
      await Given('User is in "any page except last" of My Patients page', null, { myPatientPageFixture }); 
      await When('User clicks "last page (>>)" arrow', null, { myPatientPageFixture }); 
      await Then('"Last page of patient records" should be displayed', null, { myPatientPageFixture }); 
    });

  });

  test('Verify pagination count and controls', async ({ Given, When, Then, And, myPatientPageFixture }) => { 
    await Given('User is in any page of My Patients page', null, { myPatientPageFixture }); 
    await When('User navigates to any page', null, { myPatientPageFixture }); 
    await Then('Pagination text should display correct range and total number of patients', null, { myPatientPageFixture }); 
    await And('Pagination controls should be displayed', null, { myPatientPageFixture }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests\\features\\02Mypatients.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":9,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then Page header \"My Patients\" should be displayed","stepMatchArguments":[{"group":{"start":12,"value":"\"My Patients\"","children":[{"start":13,"value":"My Patients","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"And Search bar should be displayed","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"And Search icon should be displayed inside the search bar","stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"And Placeholder text \"Search...\" should be displayed","stepMatchArguments":[{"group":{"start":17,"value":"\"Search...\"","children":[{"start":18,"value":"Search...","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":19,"pickleLine":16,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":20,"gherkinStepLine":17,"keywordType":"Outcome","textWithKeyword":"Then following table headers should be displayed","stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"And following columns should have sorting icons","stepMatchArguments":[]}]},
  {"pwTestLine":24,"pickleLine":29,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":25,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"Then All columns should have values","stepMatchArguments":[]},{"pwStepLine":26,"gherkinStepLine":31,"keywordType":"Outcome","textWithKeyword":"And each patient record should contain","stepMatchArguments":[]},{"pwStepLine":27,"gherkinStepLine":34,"keywordType":"Outcome","textWithKeyword":"And Details column should display following for each patient","stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":38,"keywordType":"Outcome","textWithKeyword":"And Details should be displayed in multiline format","stepMatchArguments":[]}]},
  {"pwTestLine":33,"pickleLine":46,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":34,"gherkinStepLine":42,"keywordType":"Outcome","textWithKeyword":"Then \"Email\" should be displayed in \"valid email\" format for each patient record","stepMatchArguments":[{"group":{"start":0,"value":"\"Email\"","children":[{"start":1,"value":"Email","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":31,"value":"\"valid email\"","children":[{"start":32,"value":"valid email","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":37,"pickleLine":47,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":38,"gherkinStepLine":42,"keywordType":"Outcome","textWithKeyword":"Then \"Phone number\" should be displayed in \"valid digits\" format for each patient record","stepMatchArguments":[{"group":{"start":0,"value":"\"Phone number\"","children":[{"start":1,"value":"Phone number","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":38,"value":"\"valid digits\"","children":[{"start":39,"value":"valid digits","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":41,"pickleLine":48,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":42,"keywordType":"Outcome","textWithKeyword":"Then \"Date of birth\" should be displayed in \"dd-mm-yyyy\" format for each patient record","stepMatchArguments":[{"group":{"start":0,"value":"\"Date of birth\"","children":[{"start":1,"value":"Date of birth","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"dd-mm-yyyy\"","children":[{"start":40,"value":"dd-mm-yyyy","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":45,"pickleLine":49,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":42,"keywordType":"Outcome","textWithKeyword":"Then \"Last visit date\" should be displayed in \"dd-mm-yyyy\" format for each patient record","stepMatchArguments":[{"group":{"start":0,"value":"\"Last visit date\"","children":[{"start":1,"value":"Last visit date","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"dd-mm-yyyy\"","children":[{"start":42,"value":"dd-mm-yyyy","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":51,"pickleLine":52,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":53,"keywordType":"Outcome","textWithKeyword":"Then following actions should be available for each patient","stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":57,"keywordType":"Outcome","textWithKeyword":"And Edit icon should be displayed for each patient record","stepMatchArguments":[]},{"pwStepLine":54,"gherkinStepLine":58,"keywordType":"Outcome","textWithKeyword":"And Delete icon should be displayed for each patient record","stepMatchArguments":[]}]},
  {"pwTestLine":57,"pickleLine":61,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":58,"gherkinStepLine":62,"keywordType":"Context","textWithKeyword":"Given User logged into the application without patient records","stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":63,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","stepMatchArguments":[]},{"pwStepLine":61,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then My Patients page should display empty table","stepMatchArguments":[]}]},
  {"pwTestLine":66,"pickleLine":76,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":67,"gherkinStepLine":70,"keywordType":"Context","textWithKeyword":"Given User is in My Patients page","stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When User clicks \"up\" arrow on \"Patient Id\" column","stepMatchArguments":[{"group":{"start":12,"value":"\"up\"","children":[{"start":13,"value":"up","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":26,"value":"\"Patient Id\"","children":[{"start":27,"value":"Patient Id","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":69,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then Patient records should be sorted in \"ascending\" order by \"Patient Id\"","stepMatchArguments":[{"group":{"start":36,"value":"\"ascending\"","children":[{"start":37,"value":"ascending","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":57,"value":"\"Patient Id\"","children":[{"start":58,"value":"Patient Id","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":72,"pickleLine":77,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":73,"gherkinStepLine":70,"keywordType":"Context","textWithKeyword":"Given User is in My Patients page","stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When User clicks \"down\" arrow on \"Patient Id\" column","stepMatchArguments":[{"group":{"start":12,"value":"\"down\"","children":[{"start":13,"value":"down","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":28,"value":"\"Patient Id\"","children":[{"start":29,"value":"Patient Id","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then Patient records should be sorted in \"descending\" order by \"Patient Id\"","stepMatchArguments":[{"group":{"start":36,"value":"\"descending\"","children":[{"start":37,"value":"descending","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":58,"value":"\"Patient Id\"","children":[{"start":59,"value":"Patient Id","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":78,"pickleLine":78,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":79,"gherkinStepLine":70,"keywordType":"Context","textWithKeyword":"Given User is in My Patients page","stepMatchArguments":[]},{"pwStepLine":80,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When User clicks \"up\" arrow on \"Name\" column","stepMatchArguments":[{"group":{"start":12,"value":"\"up\"","children":[{"start":13,"value":"up","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":26,"value":"\"Name\"","children":[{"start":27,"value":"Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":81,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then Patient records should be sorted in \"ascending\" order by \"Name\"","stepMatchArguments":[{"group":{"start":36,"value":"\"ascending\"","children":[{"start":37,"value":"ascending","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":57,"value":"\"Name\"","children":[{"start":58,"value":"Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":84,"pickleLine":79,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":85,"gherkinStepLine":70,"keywordType":"Context","textWithKeyword":"Given User is in My Patients page","stepMatchArguments":[]},{"pwStepLine":86,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When User clicks \"down\" arrow on \"Name\" column","stepMatchArguments":[{"group":{"start":12,"value":"\"down\"","children":[{"start":13,"value":"down","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":28,"value":"\"Name\"","children":[{"start":29,"value":"Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then Patient records should be sorted in \"descending\" order by \"Name\"","stepMatchArguments":[{"group":{"start":36,"value":"\"descending\"","children":[{"start":37,"value":"descending","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":58,"value":"\"Name\"","children":[{"start":59,"value":"Name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":94,"pickleLine":89,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":95,"gherkinStepLine":83,"keywordType":"Context","textWithKeyword":"Given User is in My Patients page","stepMatchArguments":[]},{"pwStepLine":96,"gherkinStepLine":84,"keywordType":"Action","textWithKeyword":"When User searches using \"patient name\"","stepMatchArguments":[{"group":{"start":20,"value":"\"patient name\"","children":[{"start":21,"value":"patient name","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":97,"gherkinStepLine":85,"keywordType":"Outcome","textWithKeyword":"Then Matching patient details should be displayed","stepMatchArguments":[]}]},
  {"pwTestLine":100,"pickleLine":90,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":101,"gherkinStepLine":83,"keywordType":"Context","textWithKeyword":"Given User is in My Patients page","stepMatchArguments":[]},{"pwStepLine":102,"gherkinStepLine":84,"keywordType":"Action","textWithKeyword":"When User searches using \"patient id\"","stepMatchArguments":[{"group":{"start":20,"value":"\"patient id\"","children":[{"start":21,"value":"patient id","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":103,"gherkinStepLine":85,"keywordType":"Outcome","textWithKeyword":"Then Matching patient details should be displayed","stepMatchArguments":[]}]},
  {"pwTestLine":108,"pickleLine":92,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":109,"gherkinStepLine":93,"keywordType":"Context","textWithKeyword":"Given User is in My Patients page","stepMatchArguments":[]},{"pwStepLine":110,"gherkinStepLine":94,"keywordType":"Context","textWithKeyword":"And User entered text in search box","stepMatchArguments":[]},{"pwStepLine":111,"gherkinStepLine":95,"keywordType":"Action","textWithKeyword":"When User clears the search text","stepMatchArguments":[]},{"pwStepLine":112,"gherkinStepLine":96,"keywordType":"Outcome","textWithKeyword":"Then All patient records should be displayed again","stepMatchArguments":[]}]},
  {"pwTestLine":117,"pickleLine":106,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":118,"gherkinStepLine":100,"keywordType":"Context","textWithKeyword":"Given User is in \"multiple pages of patient records\" of My Patients page","stepMatchArguments":[{"group":{"start":11,"value":"\"multiple pages of patient records\"","children":[{"start":12,"value":"multiple pages of patient records","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":119,"gherkinStepLine":101,"keywordType":"Action","textWithKeyword":"When User clicks \"next page (>)\" arrow","stepMatchArguments":[{"group":{"start":12,"value":"\"next page (>)\"","children":[{"start":13,"value":"next page (>)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":120,"gherkinStepLine":102,"keywordType":"Outcome","textWithKeyword":"Then \"Next set of patient records\" should be displayed","stepMatchArguments":[{"group":{"start":0,"value":"\"Next set of patient records\"","children":[{"start":1,"value":"Next set of patient records","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":123,"pickleLine":107,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":124,"gherkinStepLine":100,"keywordType":"Context","textWithKeyword":"Given User is in \"last page\" of My Patients page","stepMatchArguments":[{"group":{"start":11,"value":"\"last page\"","children":[{"start":12,"value":"last page","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":125,"gherkinStepLine":101,"keywordType":"Action","textWithKeyword":"When User clicks \"previous page (<)\" arrow","stepMatchArguments":[{"group":{"start":12,"value":"\"previous page (<)\"","children":[{"start":13,"value":"previous page (<)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":126,"gherkinStepLine":102,"keywordType":"Outcome","textWithKeyword":"Then \"Previous set of patient records\" should be displayed","stepMatchArguments":[{"group":{"start":0,"value":"\"Previous set of patient records\"","children":[{"start":1,"value":"Previous set of patient records","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":129,"pickleLine":108,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":130,"gherkinStepLine":100,"keywordType":"Context","textWithKeyword":"Given User is in \"any page except first\" of My Patients page","stepMatchArguments":[{"group":{"start":11,"value":"\"any page except first\"","children":[{"start":12,"value":"any page except first","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":131,"gherkinStepLine":101,"keywordType":"Action","textWithKeyword":"When User clicks \"first page (<<)\" arrow","stepMatchArguments":[{"group":{"start":12,"value":"\"first page (<<)\"","children":[{"start":13,"value":"first page (<<)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":132,"gherkinStepLine":102,"keywordType":"Outcome","textWithKeyword":"Then \"First page of patient records\" should be displayed","stepMatchArguments":[{"group":{"start":0,"value":"\"First page of patient records\"","children":[{"start":1,"value":"First page of patient records","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":135,"pickleLine":109,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":136,"gherkinStepLine":100,"keywordType":"Context","textWithKeyword":"Given User is in \"any page except last\" of My Patients page","stepMatchArguments":[{"group":{"start":11,"value":"\"any page except last\"","children":[{"start":12,"value":"any page except last","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":137,"gherkinStepLine":101,"keywordType":"Action","textWithKeyword":"When User clicks \"last page (>>)\" arrow","stepMatchArguments":[{"group":{"start":12,"value":"\"last page (>>)\"","children":[{"start":13,"value":"last page (>>)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":138,"gherkinStepLine":102,"keywordType":"Outcome","textWithKeyword":"Then \"Last page of patient records\" should be displayed","stepMatchArguments":[{"group":{"start":0,"value":"\"Last page of patient records\"","children":[{"start":1,"value":"Last page of patient records","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":143,"pickleLine":112,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given User is logged into the application","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And User is in dietician application dashboard page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks on My Patients button","isBg":true,"stepMatchArguments":[]},{"pwStepLine":144,"gherkinStepLine":113,"keywordType":"Context","textWithKeyword":"Given User is in any page of My Patients page","stepMatchArguments":[]},{"pwStepLine":145,"gherkinStepLine":114,"keywordType":"Action","textWithKeyword":"When User navigates to any page","stepMatchArguments":[]},{"pwStepLine":146,"gherkinStepLine":115,"keywordType":"Outcome","textWithKeyword":"Then Pagination text should display correct range and total number of patients","stepMatchArguments":[]},{"pwStepLine":147,"gherkinStepLine":116,"keywordType":"Outcome","textWithKeyword":"And Pagination controls should be displayed","stepMatchArguments":[]}]},
]; // bdd-data-end