// Generated from: tests\features\05EditPatient.feature
import { test } from "../../../tests/fixtures/customFixtures.js";

test.describe('To test the Edit Patient Details page functionality', () => {

  test.describe('To test the display of Edit Patient page dialog box', () => {

    test('Example #1', { tag: ['@smoke', '@regression', '@editPatientElementsDisplay'] }, async ({ When, Then, editPatientFixture }) => { 
      await When('User clicks the Edit Icon button of a patient', null, { editPatientFixture }); 
      await Then('User should see the "pageTitle" in the edit patient page', null, { editPatientFixture }); 
    });

    test('Example #2', { tag: ['@smoke', '@regression', '@editPatientElementsDisplay'] }, async ({ When, Then, editPatientFixture }) => { 
      await When('User clicks the Edit Icon button of a patient', null, { editPatientFixture }); 
      await Then('User should see the "submitButtonPresence" in the edit patient page', null, { editPatientFixture }); 
    });

    test('Example #3', { tag: ['@smoke', '@regression', '@editPatientElementsDisplay'] }, async ({ When, Then, editPatientFixture }) => { 
      await When('User clicks the Edit Icon button of a patient', null, { editPatientFixture }); 
      await Then('User should see the "closeButtonPresence" in the edit patient page', null, { editPatientFixture }); 
    });

    test('Example #4', { tag: ['@smoke', '@regression', '@editPatientElementsDisplay'] }, async ({ When, Then, editPatientFixture }) => { 
      await When('User clicks the Edit Icon button of a patient', null, { editPatientFixture }); 
      await Then('User should see the "fileUploadOption" in the edit patient page', null, { editPatientFixture }); 
    });

    test('Example #5', { tag: ['@smoke', '@regression', '@editPatientElementsDisplay'] }, async ({ When, Then, editPatientFixture }) => { 
      await When('User clicks the Edit Icon button of a patient', null, { editPatientFixture }); 
      await Then('User should see the "uploadHealthReportLabel" in the edit patient page', null, { editPatientFixture }); 
    });

    test('Example #6', { tag: ['@smoke', '@regression', '@editPatientElementsDisplay'] }, async ({ When, Then, editPatientFixture }) => { 
      await When('User clicks the Edit Icon button of a patient', null, { editPatientFixture }); 
      await Then('User should see the "noFileChosenText" in the edit patient page', null, { editPatientFixture }); 
    });

  });

  test.describe('To test the presence of field with values entered during Patient creation', () => {

    test('Example #1', { tag: ['@regression', '@editPatientFieldValuesDisplay'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Peanuts"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Rajasthani"}]},{"cells":[{"value":"Date of Birth"},{"value":"1954-05-15"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('\'First Name\' field should display expected value \'firstName\'', null, { editPatientFixture }); 
    });

    test('Example #2', { tag: ['@regression', '@editPatientFieldValuesDisplay'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Peanuts"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Rajasthani"}]},{"cells":[{"value":"Date of Birth"},{"value":"1954-05-15"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('\'Last Name\' field should display expected value \'lastName\'', null, { editPatientFixture }); 
    });

    test('Example #3', { tag: ['@regression', '@editPatientFieldValuesDisplay'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Peanuts"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Rajasthani"}]},{"cells":[{"value":"Date of Birth"},{"value":"1954-05-15"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('\'Email\' field should display expected value \'emailId\'', null, { editPatientFixture }); 
    });

    test('Example #4', { tag: ['@regression', '@editPatientFieldValuesDisplay'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Peanuts"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Rajasthani"}]},{"cells":[{"value":"Date of Birth"},{"value":"1954-05-15"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('\'Contact Number\' field should display expected value \'contactNo\'', null, { editPatientFixture }); 
    });

    test('Example #5', { tag: ['@regression', '@editPatientFieldValuesDisplay'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Peanuts"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Rajasthani"}]},{"cells":[{"value":"Date of Birth"},{"value":"1954-05-15"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('\'Allergy\' field should display expected value \'Peanuts\'', null, { editPatientFixture }); 
    });

    test('Example #6', { tag: ['@regression', '@editPatientFieldValuesDisplay'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Peanuts"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Rajasthani"}]},{"cells":[{"value":"Date of Birth"},{"value":"1954-05-15"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('\'Food Preference\' field should display expected value \'Vegetarian\'', null, { editPatientFixture }); 
    });

    test('Example #7', { tag: ['@regression', '@editPatientFieldValuesDisplay'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Peanuts"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Rajasthani"}]},{"cells":[{"value":"Date of Birth"},{"value":"1954-05-15"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('\'Cuisine Category\' field should display expected value \'Rajasthani\'', null, { editPatientFixture }); 
    });

    test('Example #8', { tag: ['@regression', '@editPatientFieldValuesDisplay'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Peanuts"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Rajasthani"}]},{"cells":[{"value":"Date of Birth"},{"value":"1954-05-15"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('\'Date of Birth\' field should display expected value \'1954-05-15\'', null, { editPatientFixture }); 
    });

  });

  test.describe('To verify the \'<Field>\' field displays placeholder details when vital is not given', () => {

    test('Example #1', { tag: ['@regression', '@vitalsPlaceholder'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Pistachio"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Kashmiri"}]},{"cells":[{"value":"Date of Birth"},{"value":"1984-09-21"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('the "<field>" field should display the placeholder text "SP" in the Edit Patient Page', null, { editPatientFixture }); 
    });

    test('Example #2', { tag: ['@regression', '@vitalsPlaceholder'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Pistachio"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Kashmiri"}]},{"cells":[{"value":"Date of Birth"},{"value":"1984-09-21"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('the "<field>" field should display the placeholder text "DP" in the Edit Patient Page', null, { editPatientFixture }); 
    });

    test('Example #3', { tag: ['@regression', '@vitalsPlaceholder'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Pistachio"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Kashmiri"}]},{"cells":[{"value":"Date of Birth"},{"value":"1984-09-21"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('the "<field>" field should display the placeholder text "Weight" in the Edit Patient Page', null, { editPatientFixture }); 
    });

    test('Example #4', { tag: ['@regression', '@vitalsPlaceholder'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Pistachio"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Kashmiri"}]},{"cells":[{"value":"Date of Birth"},{"value":"1984-09-21"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('the "<field>" field should display the placeholder text "Height" in the Edit Patient Page', null, { editPatientFixture }); 
    });

    test('Example #5', { tag: ['@regression', '@vitalsPlaceholder'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Pistachio"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Kashmiri"}]},{"cells":[{"value":"Date of Birth"},{"value":"1984-09-21"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('the "<field>" field should display the placeholder text "Temperature" in the Edit Patient Page', null, { editPatientFixture }); 
    });

  });

  test.describe('Verify "<field>" vitals field does not have a mandatory indicator', () => {

    test('Verify "SP" vitals field does not have a mandatory indicator', { tag: ['@regression', '@vitalsFieldMandatoryIndicatorCheck'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Pistachio"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Kashmiri"}]},{"cells":[{"value":"Date of Birth"},{"value":"1984-09-21"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('the Vitals section "SP" field should NOT display a mandatory indicator in Edit Patient Page', null, { editPatientFixture }); 
    });

    test('Verify "DP" vitals field does not have a mandatory indicator', { tag: ['@regression', '@vitalsFieldMandatoryIndicatorCheck'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Pistachio"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Kashmiri"}]},{"cells":[{"value":"Date of Birth"},{"value":"1984-09-21"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('the Vitals section "DP" field should NOT display a mandatory indicator in Edit Patient Page', null, { editPatientFixture }); 
    });

    test('Verify "Weight" vitals field does not have a mandatory indicator', { tag: ['@regression', '@vitalsFieldMandatoryIndicatorCheck'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Pistachio"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Kashmiri"}]},{"cells":[{"value":"Date of Birth"},{"value":"1984-09-21"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('the Vitals section "Weight" field should NOT display a mandatory indicator in Edit Patient Page', null, { editPatientFixture }); 
    });

    test('Verify "Height" vitals field does not have a mandatory indicator', { tag: ['@regression', '@vitalsFieldMandatoryIndicatorCheck'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Pistachio"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Kashmiri"}]},{"cells":[{"value":"Date of Birth"},{"value":"1984-09-21"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('the Vitals section "Height" field should NOT display a mandatory indicator in Edit Patient Page', null, { editPatientFixture }); 
    });

    test('Verify "Temperature" vitals field does not have a mandatory indicator', { tag: ['@regression', '@vitalsFieldMandatoryIndicatorCheck'] }, async ({ Given, When, Then, editPatientFixture }) => { 
      await Given('Create a new Patient with below details', {"dataTable":{"rows":[{"cells":[{"value":"Field"},{"value":"Value"}]},{"cells":[{"value":"First Name"},{"value":"firstName"}]},{"cells":[{"value":"Last Name"},{"value":"lastName"}]},{"cells":[{"value":"Email"},{"value":"emailId"}]},{"cells":[{"value":"Contact Number"},{"value":"contactNo"}]},{"cells":[{"value":"Allergy"},{"value":"Pistachio"}]},{"cells":[{"value":"Food Preference"},{"value":"Vegetarian"}]},{"cells":[{"value":"Cuisine Category"},{"value":"Kashmiri"}]},{"cells":[{"value":"Date of Birth"},{"value":"1984-09-21"}]}]}}, { editPatientFixture }); 
      await When('User search and clicks Edit Icon of newly created patient', null, { editPatientFixture }); 
      await Then('the Vitals section "Temperature" field should NOT display a mandatory indicator in Edit Patient Page', null, { editPatientFixture }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests\\features\\05EditPatient.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":8,"pickleLine":11,"tags":["@smoke","@regression","@editPatientElementsDisplay"],"steps":[{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Edit Icon button of a patient","stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"pageTitle\" in the edit patient page","stepMatchArguments":[{"group":{"start":20,"value":"\"pageTitle\"","children":[{"start":21,"value":"pageTitle","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":13,"pickleLine":12,"tags":["@smoke","@regression","@editPatientElementsDisplay"],"steps":[{"pwStepLine":14,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Edit Icon button of a patient","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"submitButtonPresence\" in the edit patient page","stepMatchArguments":[{"group":{"start":20,"value":"\"submitButtonPresence\"","children":[{"start":21,"value":"submitButtonPresence","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":18,"pickleLine":13,"tags":["@smoke","@regression","@editPatientElementsDisplay"],"steps":[{"pwStepLine":19,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Edit Icon button of a patient","stepMatchArguments":[]},{"pwStepLine":20,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"closeButtonPresence\" in the edit patient page","stepMatchArguments":[{"group":{"start":20,"value":"\"closeButtonPresence\"","children":[{"start":21,"value":"closeButtonPresence","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":23,"pickleLine":14,"tags":["@smoke","@regression","@editPatientElementsDisplay"],"steps":[{"pwStepLine":24,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Edit Icon button of a patient","stepMatchArguments":[]},{"pwStepLine":25,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"fileUploadOption\" in the edit patient page","stepMatchArguments":[{"group":{"start":20,"value":"\"fileUploadOption\"","children":[{"start":21,"value":"fileUploadOption","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":28,"pickleLine":15,"tags":["@smoke","@regression","@editPatientElementsDisplay"],"steps":[{"pwStepLine":29,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Edit Icon button of a patient","stepMatchArguments":[]},{"pwStepLine":30,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"uploadHealthReportLabel\" in the edit patient page","stepMatchArguments":[{"group":{"start":20,"value":"\"uploadHealthReportLabel\"","children":[{"start":21,"value":"uploadHealthReportLabel","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":33,"pickleLine":16,"tags":["@smoke","@regression","@editPatientElementsDisplay"],"steps":[{"pwStepLine":34,"gherkinStepLine":6,"keywordType":"Action","textWithKeyword":"When User clicks the Edit Icon button of a patient","stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"noFileChosenText\" in the edit patient page","stepMatchArguments":[{"group":{"start":20,"value":"\"noFileChosenText\"","children":[{"start":21,"value":"noFileChosenText","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":42,"pickleLine":39,"tags":["@regression","@editPatientFieldValuesDisplay"],"steps":[{"pwStepLine":43,"gherkinStepLine":23,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":45,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then 'First Name' field should display expected value 'firstName'","stepMatchArguments":[{"group":{"start":0,"value":"'First Name'","children":[{"children":[{"children":[]}]},{"start":1,"value":"First Name","children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":49,"value":"'firstName'","children":[{"children":[{"children":[]}]},{"start":50,"value":"firstName","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":48,"pickleLine":40,"tags":["@regression","@editPatientFieldValuesDisplay"],"steps":[{"pwStepLine":49,"gherkinStepLine":23,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":50,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then 'Last Name' field should display expected value 'lastName'","stepMatchArguments":[{"group":{"start":0,"value":"'Last Name'","children":[{"children":[{"children":[]}]},{"start":1,"value":"Last Name","children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":48,"value":"'lastName'","children":[{"children":[{"children":[]}]},{"start":49,"value":"lastName","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":54,"pickleLine":41,"tags":["@regression","@editPatientFieldValuesDisplay"],"steps":[{"pwStepLine":55,"gherkinStepLine":23,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":56,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":57,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then 'Email' field should display expected value 'emailId'","stepMatchArguments":[{"group":{"start":0,"value":"'Email'","children":[{"children":[{"children":[]}]},{"start":1,"value":"Email","children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":44,"value":"'emailId'","children":[{"children":[{"children":[]}]},{"start":45,"value":"emailId","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":60,"pickleLine":42,"tags":["@regression","@editPatientFieldValuesDisplay"],"steps":[{"pwStepLine":61,"gherkinStepLine":23,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then 'Contact Number' field should display expected value 'contactNo'","stepMatchArguments":[{"group":{"start":0,"value":"'Contact Number'","children":[{"children":[{"children":[]}]},{"start":1,"value":"Contact Number","children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":53,"value":"'contactNo'","children":[{"children":[{"children":[]}]},{"start":54,"value":"contactNo","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":66,"pickleLine":43,"tags":["@regression","@editPatientFieldValuesDisplay"],"steps":[{"pwStepLine":67,"gherkinStepLine":23,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":69,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then 'Allergy' field should display expected value 'Peanuts'","stepMatchArguments":[{"group":{"start":0,"value":"'Allergy'","children":[{"children":[{"children":[]}]},{"start":1,"value":"Allergy","children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":46,"value":"'Peanuts'","children":[{"children":[{"children":[]}]},{"start":47,"value":"Peanuts","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":72,"pickleLine":44,"tags":["@regression","@editPatientFieldValuesDisplay"],"steps":[{"pwStepLine":73,"gherkinStepLine":23,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":75,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then 'Food Preference' field should display expected value 'Vegetarian'","stepMatchArguments":[{"group":{"start":0,"value":"'Food Preference'","children":[{"children":[{"children":[]}]},{"start":1,"value":"Food Preference","children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"'Vegetarian'","children":[{"children":[{"children":[]}]},{"start":55,"value":"Vegetarian","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":78,"pickleLine":45,"tags":["@regression","@editPatientFieldValuesDisplay"],"steps":[{"pwStepLine":79,"gherkinStepLine":23,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":80,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":81,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then 'Cuisine Category' field should display expected value 'Rajasthani'","stepMatchArguments":[{"group":{"start":0,"value":"'Cuisine Category'","children":[{"children":[{"children":[]}]},{"start":1,"value":"Cuisine Category","children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":55,"value":"'Rajasthani'","children":[{"children":[{"children":[]}]},{"start":56,"value":"Rajasthani","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":84,"pickleLine":46,"tags":["@regression","@editPatientFieldValuesDisplay"],"steps":[{"pwStepLine":85,"gherkinStepLine":23,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":86,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":87,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then 'Date of Birth' field should display expected value '1954-05-15'","stepMatchArguments":[{"group":{"start":0,"value":"'Date of Birth'","children":[{"children":[{"children":[]}]},{"start":1,"value":"Date of Birth","children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":52,"value":"'1954-05-15'","children":[{"children":[{"children":[]}]},{"start":53,"value":"1954-05-15","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":94,"pickleLine":68,"tags":["@regression","@vitalsPlaceholder"],"steps":[{"pwStepLine":95,"gherkinStepLine":53,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":96,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":97,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then the \"<field>\" field should display the placeholder text \"SP\" in the Edit Patient Page","stepMatchArguments":[{"group":{"start":4,"value":"\"<field>\"","children":[{"start":5,"value":"<field>","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":56,"value":"\"SP\"","children":[{"start":57,"value":"SP","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":100,"pickleLine":69,"tags":["@regression","@vitalsPlaceholder"],"steps":[{"pwStepLine":101,"gherkinStepLine":53,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":102,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":103,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then the \"<field>\" field should display the placeholder text \"DP\" in the Edit Patient Page","stepMatchArguments":[{"group":{"start":4,"value":"\"<field>\"","children":[{"start":5,"value":"<field>","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":56,"value":"\"DP\"","children":[{"start":57,"value":"DP","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":106,"pickleLine":70,"tags":["@regression","@vitalsPlaceholder"],"steps":[{"pwStepLine":107,"gherkinStepLine":53,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":108,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":109,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then the \"<field>\" field should display the placeholder text \"Weight\" in the Edit Patient Page","stepMatchArguments":[{"group":{"start":4,"value":"\"<field>\"","children":[{"start":5,"value":"<field>","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":56,"value":"\"Weight\"","children":[{"start":57,"value":"Weight","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":112,"pickleLine":71,"tags":["@regression","@vitalsPlaceholder"],"steps":[{"pwStepLine":113,"gherkinStepLine":53,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":114,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":115,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then the \"<field>\" field should display the placeholder text \"Height\" in the Edit Patient Page","stepMatchArguments":[{"group":{"start":4,"value":"\"<field>\"","children":[{"start":5,"value":"<field>","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":56,"value":"\"Height\"","children":[{"start":57,"value":"Height","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":118,"pickleLine":72,"tags":["@regression","@vitalsPlaceholder"],"steps":[{"pwStepLine":119,"gherkinStepLine":53,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":120,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":121,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then the \"<field>\" field should display the placeholder text \"Temperature\" in the Edit Patient Page","stepMatchArguments":[{"group":{"start":4,"value":"\"<field>\"","children":[{"start":5,"value":"<field>","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":56,"value":"\"Temperature\"","children":[{"start":57,"value":"Temperature","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":128,"pickleLine":92,"tags":["@regression","@vitalsFieldMandatoryIndicatorCheck"],"steps":[{"pwStepLine":129,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":130,"gherkinStepLine":87,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":131,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"Then the Vitals section \"SP\" field should NOT display a mandatory indicator in Edit Patient Page","stepMatchArguments":[{"group":{"start":19,"value":"\"SP\"","children":[{"start":20,"value":"SP","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":134,"pickleLine":93,"tags":["@regression","@vitalsFieldMandatoryIndicatorCheck"],"steps":[{"pwStepLine":135,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":136,"gherkinStepLine":87,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":137,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"Then the Vitals section \"DP\" field should NOT display a mandatory indicator in Edit Patient Page","stepMatchArguments":[{"group":{"start":19,"value":"\"DP\"","children":[{"start":20,"value":"DP","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":140,"pickleLine":94,"tags":["@regression","@vitalsFieldMandatoryIndicatorCheck"],"steps":[{"pwStepLine":141,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":142,"gherkinStepLine":87,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":143,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"Then the Vitals section \"Weight\" field should NOT display a mandatory indicator in Edit Patient Page","stepMatchArguments":[{"group":{"start":19,"value":"\"Weight\"","children":[{"start":20,"value":"Weight","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":146,"pickleLine":95,"tags":["@regression","@vitalsFieldMandatoryIndicatorCheck"],"steps":[{"pwStepLine":147,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":148,"gherkinStepLine":87,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":149,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"Then the Vitals section \"Height\" field should NOT display a mandatory indicator in Edit Patient Page","stepMatchArguments":[{"group":{"start":19,"value":"\"Height\"","children":[{"start":20,"value":"Height","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":152,"pickleLine":96,"tags":["@regression","@vitalsFieldMandatoryIndicatorCheck"],"steps":[{"pwStepLine":153,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"Given Create a new Patient with below details","stepMatchArguments":[]},{"pwStepLine":154,"gherkinStepLine":87,"keywordType":"Action","textWithKeyword":"When User search and clicks Edit Icon of newly created patient","stepMatchArguments":[]},{"pwStepLine":155,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"Then the Vitals section \"Temperature\" field should NOT display a mandatory indicator in Edit Patient Page","stepMatchArguments":[{"group":{"start":19,"value":"\"Temperature\"","children":[{"start":20,"value":"Temperature","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end